apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  ports:
  - port: 80
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.mysql.password }}
        volumeMounts:
        - name: web-data
          mountPath: /var/www/html
      volumes:
      - name: web-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wordpress-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wordpress-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wordpress.storage }}
